node build/bin/hello.js all ../rcsb/2e/12e8.cif allPicture && 
node build/bin/hello.js all ../rcsb/2e/12e8.cif allPicture && 
node build/bin/hello.js all ../rcsb/5c/15c8.cif allPicture && 
node build/bin/hello.js all ../rcsb/5c/15c8.cif allPicture && 
node build/bin/hello.js all ../rcsb/a0/1a0q.cif allPicture && 
node build/bin/hello.js all ../rcsb/a0/1a0q.cif allPicture && 
node build/bin/hello.js all ../rcsb/a3/1a3l.cif allPicture && 
node build/bin/hello.js all ../rcsb/a3/1a3l.cif allPicture && 
node build/bin/hello.js all ../rcsb/a3/1a3r.cif allPicture && 
node build/bin/hello.js all ../rcsb/a3/1a3r.cif allPicture && 
node build/bin/hello.js all ../rcsb/a4/1a4j.cif allPicture && 
node build/bin/hello.js all ../rcsb/a4/1a4j.cif allPicture && 
node build/bin/hello.js all ../rcsb/a4/1a4k.cif allPicture && 
node build/bin/hello.js all ../rcsb/a4/1a4k.cif allPicture && 
node build/bin/hello.js all ../rcsb/a5/1a5f.cif allPicture && 
node build/bin/hello.js all ../rcsb/a5/1a5f.cif allPicture && 
node build/bin/hello.js all ../rcsb/a6/1a6t.cif allPicture && 
node build/bin/hello.js all ../rcsb/a6/1a6t.cif allPicture && 
node build/bin/hello.js all ../rcsb/a8/1a8j.cif allPicture && 
node build/bin/hello.js all ../rcsb/ac/1acy.cif allPicture && 
node build/bin/hello.js all ../rcsb/ac/1acy.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1ad0.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1ad0.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1ad9.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1ad9.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1adq.cif allPicture && 
node build/bin/hello.js all ../rcsb/ad/1adq.cif allPicture && 
node build/bin/hello.js all ../rcsb/ae/1ae6.cif allPicture && 
node build/bin/hello.js all ../rcsb/ae/1ae6.cif allPicture && 
node build/bin/hello.js all ../rcsb/af/1afv.cif allPicture && 
node build/bin/hello.js all ../rcsb/af/1afv.cif allPicture && 
node build/bin/hello.js all ../rcsb/ah/1ahw.cif allPicture && 
node build/bin/hello.js all ../rcsb/ah/1ahw.cif allPicture && 
node build/bin/hello.js all ../rcsb/ai/1ai1.cif allPicture && 
node build/bin/hello.js all ../rcsb/ai/1ai1.cif allPicture && 
node build/bin/hello.js all ../rcsb/ai/1aif.cif allPicture && 
node build/bin/hello.js all ../rcsb/ai/1aif.cif allPicture && 
node build/bin/hello.js all ../rcsb/aj/1aj7.cif allPicture && 
node build/bin/hello.js all ../rcsb/aj/1aj7.cif allPicture && 
node build/bin/hello.js all ../rcsb/aq/1aqk.cif allPicture && 
node build/bin/hello.js all ../rcsb/aq/1aqk.cif allPicture && 
node build/bin/hello.js all ../rcsb/ax/1axs.cif allPicture && 
node build/bin/hello.js all ../rcsb/ax/1axs.cif allPicture && 
node build/bin/hello.js all ../rcsb/ax/1axt.cif allPicture && 
node build/bin/hello.js all ../rcsb/ax/1axt.cif allPicture && 
node build/bin/hello.js all ../rcsb/ay/1ay1.cif allPicture && 
node build/bin/hello.js all ../rcsb/ay/1ay1.cif allPicture && 
node build/bin/hello.js all ../rcsb/b2/1b2w.cif allPicture && 
node build/bin/hello.js all ../rcsb/b2/1b2w.cif allPicture && 
node build/bin/hello.js all ../rcsb/b4/1b4j.cif allPicture && 
node build/bin/hello.js all ../rcsb/b4/1b4j.cif allPicture && 
node build/bin/hello.js all ../rcsb/b6/1b6d.cif allPicture && 
node build/bin/hello.js all ../rcsb/ba/1baf.cif allPicture && 
node build/bin/hello.js all ../rcsb/ba/1baf.cif allPicture && 
node build/bin/hello.js all ../rcsb/bb/1bbd.cif allPicture && 
node build/bin/hello.js all ../rcsb/bb/1bbd.cif allPicture && 
node build/bin/hello.js all ../rcsb/bb/1bbj.cif allPicture && 
node build/bin/hello.js all ../rcsb/bb/1bbj.cif allPicture && 
node build/bin/hello.js all ../rcsb/be/1bey.cif allPicture && 
node build/bin/hello.js all ../rcsb/be/1bey.cif allPicture && 
node build/bin/hello.js all ../rcsb/bf/1bfo.cif allPicture && 
node build/bin/hello.js all ../rcsb/bf/1bfo.cif allPicture && 
node build/bin/hello.js all ../rcsb/bg/1bgx.cif allPicture && 
node build/bin/hello.js all ../rcsb/bg/1bgx.cif allPicture && 
node build/bin/hello.js all ../rcsb/bj/1bj1.cif allPicture && 
node build/bin/hello.js all ../rcsb/bj/1bj1.cif allPicture && 
node build/bin/hello.js all ../rcsb/bj/1bjm.cif allPicture && 
node build/bin/hello.js all ../rcsb/bl/1bln.cif allPicture && 
node build/bin/hello.js all ../rcsb/bl/1bln.cif allPicture && 
node build/bin/hello.js all ../rcsb/bm/1bm3.cif allPicture && 
node build/bin/hello.js all ../rcsb/bm/1bm3.cif allPicture && 
node build/bin/hello.js all ../rcsb/bo/1bog.cif allPicture && 
node build/bin/hello.js all ../rcsb/bo/1bog.cif allPicture && 
node build/bin/hello.js all ../rcsb/bq/1bql.cif allPicture 